export const GET_CONVERSIONS_CORRENCIES = 'GET_CONVERSIONS_CORRENCIES'
export const GET_ENTERED_USERS_DATA = 'GET_ENTERED_USERS_DATA'
export const GET_SELECTED_USERS_CURRENCIE = 'GET_SELECTED_USERS_CURRENCIE'
export const GET_REQUEST_ERROR = 'GET_REQUEST_ERROR'
