export const GET_ENTERED_DATA_OF_USER = 'GET_ENTERED_DATA_OF_USER'
export const GET_SELECTED_CURRENCIES_OF_USER = 'GET_SELECTED_CURRENCIES_OF_USER'
export const GET_ERROR_OF_REQUEST = 'GET_ERROR_OF_REQUEST'
export const REQUEST_CONVERSIONS_FOR_CONVERTER = 'REQUEST_CONVERSIONS_FOR_CONVERTER'
